name: Deploy to GitHub-Pages

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check Out
        uses: actions/checkout@v2.4.0
        with:
          persist-credentials: false

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '16.x'

      - name: Installing NPM packages
        run: |
          if [ -d 'project' ]; then cd project && npm ci; else echo 'Skip. The project directory does not exist'; fi

      - name: Testing
        run: |
          if [ -d 'project' ]; then cd project && npm test && npm run lint; else echo 'Skip. The project directory does not exist'; fi

      - name: Building
        run: |
          if [ -d 'project' ]; then cd project && npm run build; else echo 'Skip. The project directory does not exist'; fi

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          folder: ./project/build
          branch: gh-pages
